
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hoang
 */
public class ThreeDesCipher extends javax.swing.JFrame {

    /**
     * Creates new form ThreeDesCipher
     */
    private static final String netbeansPath = "C:\\Users\\hoang\\Documents\\DES-Cipher";
    final JFileChooser fChooser;
    Des des;

    public ThreeDesCipher() {
        initComponents();
        fChooser = new JFileChooser(netbeansPath);
        des = new Des();
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encrypt = new javax.swing.JButton();
        decrypt = new javax.swing.JButton();
        key1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        key2 = new javax.swing.JTextField();
        genarateKey1 = new javax.swing.JButton();
        genarateKey2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        encrypt.setText("Encypt");
        encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptActionPerformed(evt);
            }
        });

        decrypt.setText("Decrypt");
        decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptActionPerformed(evt);
            }
        });

        key1.setText("75536BB8722AAFDD");

        jLabel1.setText("Key 1:");

        jLabel2.setText("Key 2:");

        key2.setText("15C7B0CFBB54E567");

        genarateKey1.setText("Gen key 1");
        genarateKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genarateKey1ActionPerformed(evt);
            }
        });

        genarateKey2.setText("Gen key 2");
        genarateKey2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genarateKey2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(encrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(decrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(key1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(key2)))
                    .addComponent(genarateKey1)
                    .addComponent(genarateKey2))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(encrypt)
                .addGap(18, 18, 18)
                .addComponent(decrypt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(genarateKey1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genarateKey2)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptActionPerformed
        // TODO add your handling code here:
        threeDesEncrypt();
    }//GEN-LAST:event_encryptActionPerformed

    private void genarateKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genarateKey1ActionPerformed
        // TODO add your handling code here:
        String genKey = des.generateKey(16);
        key1.setText(genKey);
    }//GEN-LAST:event_genarateKey1ActionPerformed

    private void genarateKey2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genarateKey2ActionPerformed
        // TODO add your handling code here:
        String genKey = des.generateKey(16);
        key2.setText(genKey);
    }//GEN-LAST:event_genarateKey2ActionPerformed

    private void decryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptActionPerformed
        // TODO add your handling code here:
        threeDesDecrypt();
    }//GEN-LAST:event_decryptActionPerformed

    private void threeDesEncrypt() {
        File file = openFile();
        if (file != null) {
            byte[] fileByte = FileR.readFile(file);

            String key = key1.getText();
            byte[] decFileByte = des.decryptFile(fileByte, key);
            System.out.println(decFileByte);
            String key3 = key2.getText();
            byte[] encFileByte = des.encryptFile(decFileByte, key3);
            displayGuiMessage("File " + file.getName() + " encrypted.", "Done", JOptionPane.INFORMATION_MESSAGE);
            File encFile = saveFile();
            Path path = encFile.toPath();
            try {
                Files.write(path, encFileByte);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
    
    private void threeDesDecrypt() {
         File file = openFile();
        if (file != null) {
            byte[] fileByte = FileR.readFile(file);

            String Key2 = key2.getText();
            byte[] decFileByte = des.decryptFile(fileByte, Key2);
            String Key1 = key1.getText();
            byte[] encFileByte = des.encryptFile(decFileByte, Key1);
            String Key3 = "770DD5180AC82461";
            byte[] threeDecFileByte = des.decryptFile(encFileByte, Key3);
            displayGuiMessage("File " + file.getName() + " encrypted.", "Done", JOptionPane.INFORMATION_MESSAGE);
            File encFile = saveFile();
            Path path = encFile.toPath();
            try {
                Files.write(path, threeDecFileByte);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
    
    private File openFile() {
        int openState = fChooser.showOpenDialog(this);

        if (openState == JFileChooser.APPROVE_OPTION) {
            return fChooser.getSelectedFile();
        } else {
            return null;
        }
    }

    private File saveFile() {
        int saveState = fChooser.showSaveDialog(this);

        if (saveState == JFileChooser.APPROVE_OPTION) {
            return fChooser.getSelectedFile();
        } else {
            return null;
        }
    }

    private void displayGuiMessage(String message, String windowTitle, int JOptionPaneMessType) {
        JOptionPane.showMessageDialog(this, message, windowTitle, JOptionPaneMessType);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreeDesCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreeDesCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreeDesCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreeDesCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThreeDesCipher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton decrypt;
    private javax.swing.JButton encrypt;
    private javax.swing.JButton genarateKey1;
    private javax.swing.JButton genarateKey2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField key1;
    private javax.swing.JTextField key2;
    // End of variables declaration//GEN-END:variables
}
